// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	OrdersBoler string
	UsersBoiler string
}{
	OrdersBoler: "orders_boler",
	UsersBoiler: "users_boiler",
}
