package sql_boiler

import (
	"database/sql"
	_ "github.com/lib/pq"
	"log"
)

func CreateTableForSQLBoiler(conn *sql.DB) error {

	_, err := conn.Exec(
		`CREATE TABLE IF NOT EXISTS users_boiler (
			id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  			name varchar not null,
  			age int not null,
  			created_at timestamp default now()
);`)

	_, err = conn.Exec(
		`CREATE TABLE IF NOT EXISTS orders_boler (
			id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			name varchar(32),
			amount int,
			price int,
			user_orders_id BIGINT,
			created_at timestamp default now()
);`)

	return err
}

func SQLConnect() *sql.DB {
	db, err := sql.Open("postgres", "postgres://postgres:root@localhost:5433/postgres?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}

	return db
}
